@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Oct 17 14:38:08 +0700 2024
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim SIM_VOLK_time_impl -key {Post-Implementation:sim_1:Timing:SIM_VOLK} -tclbatch SIM_VOLK.tcl -view G:/Lab1/project_1/SIM_VOLK_func_impl.wcfg -log simulate.log"
call xsim  SIM_VOLK_time_impl -key {Post-Implementation:sim_1:Timing:SIM_VOLK} -tclbatch SIM_VOLK.tcl -view G:/Lab1/project_1/SIM_VOLK_func_impl.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
